---


- name: Add Docker's key.
  become: true
  ansible.builtin.apt_key:
    url: https://download.docker.com/linux/ubuntu/gpg
    keyring: /etc/apt/trusted.gpg.d/docker.gpg

- name: Add docker repo
  become: true
  ansible.builtin.apt_repository:
    repo: deb https://download.docker.com/linux/ubuntu jammy stable
    state: present
    filename: docker

- name: install containerd.
  become: true
  ansible.builtin.package:
    name: containerd.io
    state: present

- name: Generate default containerd config.
  become: true
  ansible.builtin.shell: containerd config default > /etc/containerd/config.toml


- name: Enable systemd integration for containerd.
  become: true
  ansible.builtin.lineinfile:
    path: /etc/containerd/config.toml
    regexp: 'SystemdCgroup = false'
    line: '            SystemdCgroup = true'
  
- name: enabled and start containerd.
  become: true
  ansible.builtin.systemd:
    name: containerd
    enabled: yes
    state: restarted

