---
- name: install keepalived/
  become: true
  ansible.builtin.package:
    name: keepalived
    state: present
- name: Deploy keepalived.conf
  become: true
  ansible.builtin.template:
    src: keepalived.conf.j2
    dest: /etc/keepalived/keepalived.conf
    mode: 644
- name: enabled and start containerd.
  become: true
  ansible.builtin.systemd:
    name: keepalived
    enabled: yes
    state: started