---
- name: Add keys.
  include_tasks: key.yml
- name: Setup hostname.
  include_tasks: hostname.yml
- name: Setup containers.
  include_tasks: container.yml
- name: Setup users.
  include_tasks: user.yml
- name: Setup filesystem.
  include_tasks: filesystem.yml
- name: Setup keepalived.
  include_tasks: keepalived.yml
- name: System tunning.
  include_tasks: system.yml

